version: "2.3"

services:
  generator:
    image: carlasim/eva:latest
    privileged: true
    runtime: nvidia
    working_dir: /home/eva/visualroad
    volumes:
      - .:/home/eva/visualroad
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - OUTPUT_PATH=/home/eva/visualroad
    entrypoint: python3 /home/eva/visualroad/generator.py
    #command: tail -F anything

  driver:
    image: visualroad/core:latest
    runtime: nvidia
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: python3 /home/eva/visualroad/driver.py

  verifier:
    image: visualroad/core:latest
    runtime: nvidia
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: python3 /home/eva/visualroad/verifier.py

